databases:
  - name: bot_db
    databaseName: botdb
    user: botuser

services:
  - type: web
    name: telegram-ai-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: PG_HOST
        fromDatabase:
          name: bot_db
          property: host
      - key: PG_PORT
        fromDatabase:
          name: bot_db
          property: port
      - key: PG_DATABASE
        fromDatabase:
          name: bot_db
          property: database
      - key: PG_USER
        fromDatabase:
          name: bot_db
          property: user
      - key: PG_PASSWORD
        fromDatabase:
          name: bot_db
          property: password
      - key: BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CURRENCY_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: NEWSAPI_KEY
        sync: false
      - key: ALPHAVANTAGE_API_KEY
        sync: false
